// <auto-generated />
using System;
using AgendaMedica.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaMedica.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Especialidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuracionConsultaMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Especialidad", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Medico", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("EspecialidadMedico", b =>
                {
                    b.Property<Guid>("EspecialidadesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EspecialidadesId", "MedicoId");

                    b.HasIndex("MedicoId");

                    b.ToTable("MedicoEspecialidad", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Especialidad", b =>
                {
                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.Texto", "Nombre", b1 =>
                        {
                            b1.Property<Guid>("EspecialidadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Nombre");

                            b1.HasKey("EspecialidadId");

                            b1.ToTable("Especialidad");

                            b1.WithOwner()
                                .HasForeignKey("EspecialidadId");
                        });

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Medico", b =>
                {
                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.Texto", "ApellidoMaterno", b1 =>
                        {
                            b1.Property<Guid>("MedicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ApellidoMaterno");

                            b1.HasKey("MedicoId");

                            b1.ToTable("Medico");

                            b1.WithOwner()
                                .HasForeignKey("MedicoId");
                        });

                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.Texto", "ApellidoPaterno", b1 =>
                        {
                            b1.Property<Guid>("MedicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ApellidoPaterno");

                            b1.HasKey("MedicoId");

                            b1.ToTable("Medico");

                            b1.WithOwner()
                                .HasForeignKey("MedicoId");
                        });

                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.Texto", "Nombre", b1 =>
                        {
                            b1.Property<Guid>("MedicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nombre");

                            b1.HasKey("MedicoId");

                            b1.ToTable("Medico");

                            b1.WithOwner()
                                .HasForeignKey("MedicoId");
                        });

                    b.OwnsMany("AgendaMedica.Domain.ValueObjects.HorarioConsulta", "HorariosConsulta", b1 =>
                        {
                            b1.Property<Guid>("MedicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id1")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id1"));

                            b1.Property<int>("DiaSemana")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("HoraFin")
                                .HasColumnType("time");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time");

                            b1.HasKey("MedicoId", "Id1");

                            b1.ToTable("HorarioConsulta", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicoId");
                        });

                    b.Navigation("ApellidoMaterno")
                        .IsRequired();

                    b.Navigation("ApellidoPaterno")
                        .IsRequired();

                    b.Navigation("HorariosConsulta");

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaMedica.Domain.Entities.Paciente", b =>
                {
                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.Texto", "ApellidoMaterno", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ApellidoMaterno");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Paciente");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.Texto", "ApellidoPaterno", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ApellidoPaterno");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Paciente");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.Texto", "Nombre", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nombre");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Paciente");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.CorreoElectronico", "CorreoElectronico", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("CorreoElectronico");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Paciente");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.OwnsOne("AgendaMedica.Domain.ValueObjects.NumeroTelefono", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Telefono");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Paciente");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.Navigation("ApellidoMaterno")
                        .IsRequired();

                    b.Navigation("ApellidoPaterno")
                        .IsRequired();

                    b.Navigation("CorreoElectronico")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("EspecialidadMedico", b =>
                {
                    b.HasOne("AgendaMedica.Domain.Entities.Especialidad", null)
                        .WithMany()
                        .HasForeignKey("EspecialidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Domain.Entities.Medico", null)
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
